### PR TITLE
add needed packages to environment

### PR DESCRIPTION
**Pull request by kelle**
I had to conda install flask and bokeh before astrodbweb would work. I added these to the `conda create` line.

### CODE REVIEW

**Comment by ECGonzales** [comment]
I previously added text about the requirements.txt file to the markdown file, which includes the need for flask and a specific version of bokeh.

**Comment by kelle** [comment]
I see that now -- I had skimmed over that part. Any reason *not* to include in the initial environment creation?

**Comment by kelle** [comment]
I also don't see a requirements file in this repo.

**Comment by ECGonzales** [comment]
The requirements file is in the AstrodbWeb repo, since it is for AstrodbWeb and not the database. You don't need to have flask or bokeh in the environment if you aren't using AstrodbWeb. Maybe in the section about AstrodbWeb there should be a note to not only grab the app but also the requirements.txt file?

**Review by dr-rodriguez — APPROVED** [review]
I'd like to keep both sets of instructions so I re-added the deleted pip statement. 
An advantage of using the requirements.txt file is that you get the versions that are guaranteed to work with AstrodbWeb. It's possible later versions of flask, bokeh, numpy, etc may break the app.

**Comment by kelle** [comment]
this looks good to me!

**Review by ECGonzales — APPROVED** [review]
I agree that this new text is good.

**Comment by ECGonzales** [comment]
Shall I merge?

**Pull request merged**
